# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b7e724cc20029dc2b1741542dc2b40de705a8508566cdc35dadd8f650d206d6761b3dbac7c61413b9b0260d21d28e870c12ec710fd3c05df8aa250bf61bbad65

test:
  secret_key_base: b374d83f237d3e4212c156c0e88ada0dc3831d64195b36cedd36f66e97b66b0673d8c9de26d4cd8d31644f19fd2f10189bf8652abf8c4ac750c15da99c66ed33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
